"use client";

import React from "react";

/**
 * Customer Portal Page.
 *
 * Shows the customer their credit score, plain-language explanation
 * of the scoring factors (SHAP), and actionable improvement tips
 * generated by DiCE counterfactual explanations.
 */
export default function CustomerPage() {
  // TODO: Implement customer portal with:
  // - ScoreCard component
  // - RiskBadge component
  // - ShapWaterfall component (simplified view)
  // - DiceTips component
  return (
    <main>
      <h1>Your Credit Score</h1>
      <p>View your score, understand the factors, and learn how to improve.</p>
      {/* Placeholder: Add ScoreCard, RiskBadge, ShapWaterfall, DiceTips */}
    </main>
  );
}
