import React from "react";
import { CounterfactualTip } from "@/lib/types";

/**
 * Props for the DiceTips component.
 */
interface DiceTipsProps {
  /** List of counterfactual improvement suggestions */
  tips: CounterfactualTip[];
  /** Estimated potential score after improvements */
  potentialScore: number;
}

/**
 * DiceTips Component
 *
 * Displays actionable improvement suggestions generated by DiCE
 * counterfactual explanations. Each tip shows which features to
 * change and by how much, presented as friendly advice cards.
 */
export default function DiceTips({ tips, potentialScore }: DiceTipsProps) {
  // TODO: Implement improvement tip cards with feature change details
  return (
    <div>
      <h3>How to Improve Your Score</h3>
      <p>Potential score: {potentialScore}</p>
      {/* Placeholder: Add counterfactual tip cards */}
    </div>
  );
}
